# Generated by Django 2.2 on 2020-06-02 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField(max_length=10, verbose_name='Phone no')),
                ('image', models.ImageField(blank=True, null=True, upload_to='authorImages/')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Short Info')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('title', models.CharField(choices=[('Technology', 'Technology'), ('Health', 'Health'), ('International', 'International'), ('Politics', 'Politics'), ('Society', 'Society'), ('Economics', 'Economics'), ('Education', 'Education'), ('Tourism', 'Tourism'), ('Development', 'Development'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Entertainment', 'Entertainment')], max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Title')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='blogPostImages/')),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ['-posted'],
            },
        ),
    ]
