# Generated by Django 2.2 on 2020-06-02 13:21

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200602_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='phone',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=31, verbose_name='Phone No'),
        ),
    ]
